import { lokalMZuGeo } from './geodaten';
import type { GeoPosition, Szenario } from './types';

/**
 * Realer, öffentlich bekannter Stadtmittelpunkt Rheine (Kreis Steinfurt) -
 * wie schon bei `busunfall-b31` ein plausibler Standard-Ort, keine reale
 * Adresse und kein realer Einsatz. Die übrigen Schlüsselpunkte werden von
 * hier aus über echte Meterversätze abgeleitet (→ `domain.geodaten.projektion`),
 * damit die Distanzen zueinander automatisch stimmen.
 */
const WOHNUNGSBRAND_URSPRUNG: GeoPosition = { lat: 52.2833, lon: 7.4333 };

/**
 * @anker szenarien.liste Die Übungsszenarien - hier neue Lagen und Patienten anlegen
 *
 * Übungsszenarien. Die Vitalwerte sind so gewählt, dass die erwartete
 * Sichtungskategorie zum Einsatzbeginn dem tacSTART-Algorithmus entspricht -
 * durch den Zeitverlauf kann sie sich jedoch verändern (Nachsichtung!).
 */

/** @anker szenarien.busunfall Zehn Patienten als Vorlage für eigene Szenarien */
const busunfall: Szenario = {
  id: 'busunfall-b31',
  titel: 'Busunfall B31',
  lagemeldung:
    'Reisebus mit Schulklasse von der Fahrbahn abgekommen und umgestürzt. ' +
    'Etwa 10 Betroffene, mehrere eingeklemmt. Erster RTW vor Ort, NEF in Anfahrt.',
  einsatzhinweis:
    'Vorsichtung nach tacSTART durchführen, danach Behandlungsplatz aufbauen. ' +
    'Achtung: mindestens ein Patient verschlechtert sich im Verlauf deutlich.',
  patienten: [
    {
      id: 'B-01',
      name: 'Lena Hoffmann',
      alter: 17,
      geschlecht: 'w',
      gewicht: 58,
      kurzbefund: 'Liegt neben dem Bus, spritzende Blutung am rechten Oberschenkel.',
      untersuchungsbefund:
        'Offene Femurfraktur rechts mit arterieller Blutung, blass, kaltschweißig, ansprechbar.',
      gehfaehig: false,
      kritischeBlutung: true,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 26,
        herzfrequenz: 128,
        systolischerRR: 95,
        spo2: 96,
        gcs: 14,
        rekapzeit: 2.5,
        schmerz: 8,
      },
      probleme: [
        {
          id: 'blutung-femur',
          offensichtlich: true,
          koerperregion: 'bein_rechts',
          label: 'Arterielle Blutung Oberschenkel',
          beschreibung: 'Pulsierende Blutung aus der Wunde, Kleidung durchtränkt, Blutlache am Boden.',
          behandeltDurch: ['tourniquet', 'blutstillung'],
          verlauf: {
            systolischerRR: -6,
            herzfrequenz: 5,
            spo2: -1,
            rekapzeit: 0.15,
            gcs: -0.2,
          },
        },
      ],
      erwarteteSK: 'SK1',
    },
    {
      id: 'B-02',
      name: 'Jonas Weber',
      alter: 16,
      geschlecht: 'm',
      gewicht: 65,
      kurzbefund: 'Sitzt angelehnt am Straßenrand, atmet schnell, hält sich den Brustkorb.',
      untersuchungsbefund:
        'Prellmarke linker Thorax, abgeschwächtes Atemgeräusch links. Zunehmende Atemnot.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 28,
        herzfrequenz: 118,
        systolischerRR: 105,
        spo2: 90,
        gcs: 15,
        rekapzeit: 2,
        schmerz: 6,
      },
      probleme: [
        {
          id: 'spannungspneumothorax',
          koerperregion: 'thorax',
          label: 'Spannungspneumothorax links',
          beschreibung: 'Gestaute Halsvenen, hypersonorer Klopfschall, Atemnot nimmt zu.',
          behandeltDurch: ['thoraxentlastung'],
          startetNachMin: 3,
          verlauf: {
            spo2: -3,
            atemfrequenz: 2,
            herzfrequenz: 6,
            systolischerRR: -8,
            gcs: -0.3,
          },
        },
      ],
      erwarteteSK: 'SK2',
      auskultation: 'links kein Atemgeräusch, rechts seitengleich; hypersonorer Klopfschall links',
    },
    {
      id: 'B-03',
      name: 'Sabine Krüger',
      alter: 44,
      geschlecht: 'w',
      gewicht: 68,
      kurzbefund: 'Busfahrerin, liegt im Fahrerbereich, reagiert nicht auf Ansprache.',
      untersuchungsbefund:
        'Schweres Schädel-Hirn-Trauma, schnarchende Atmung, Blut im Mundraum.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: false,
      startVitalwerte: {
        atemfrequenz: 12,
        herzfrequenz: 96,
        systolischerRR: 130,
        spo2: 92,
        gcs: 7,
        rekapzeit: 1.8,
      },
      probleme: [
        {
          id: 'atemwegsverlegung',
          entdecktDurch: 'mundraumkontrolle',
          koerperregion: 'kopf',
          label: 'Verlegter Atemweg',
          beschreibung: 'Schnarchende Atmung, Blut und Erbrochenes im Mundraum, Zunge fällt zurück.',
          behandeltDurch: ['atemwege_freimachen', 'guedeltubus', 'wendltubus', 'intubation'],
          verlauf: { spo2: -4, gcs: -0.3, herzfrequenz: 2 },
        },
      ],
      erwarteteSK: 'SK1',
      pupillen: 'seitendifferent',
      auskultation: 'grobblasige Rasselgeräusche beidseits',
    },
    {
      id: 'B-04',
      name: 'Mehmet Yilmaz',
      alter: 52,
      geschlecht: 'm',
      gewicht: 88,
      kurzbefund: 'Im Bus eingeklemmt, klagt über Schmerzen im Becken.',
      untersuchungsbefund:
        'Instabiles Becken, deutliche Schockzeichen, technische Rettung läuft.',
      eingeklemmtBeimStart: true,
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 24,
        herzfrequenz: 132,
        systolischerRR: 78,
        spo2: 93,
        gcs: 14,
        rekapzeit: 3,
        schmerz: 7,
      },
      probleme: [
        {
          id: 'beckenfraktur',
          offensichtlich: true,
          koerperregion: 'becken',
          label: 'Instabile Beckenfraktur',
          beschreibung: 'Becken federt bei vorsichtigem Druck, Hämatom in der Leiste, blasse Haut.',
          behandeltDurch: ['beckenschlinge'],
          verlauf: { systolischerRR: -4, herzfrequenz: 4, rekapzeit: 0.1, schmerz: 0.05 },
        },
        {
          id: 'volumenmangel',
          koerperregion: 'abdomen',
          label: 'Hämorrhagischer Schock',
          beschreibung: 'Puls fadenförmig und schnell, Haut kaltschweißig, Patient zunehmend unruhig.',
          behandeltDurch: ['volumengabe', 'schocklage'],
          verlauf: { systolischerRR: -2, herzfrequenz: 2, gcs: -0.1 },
        },
      ],
      erwarteteSK: 'SK1',
      ekg: 'Sinustachykardie 130/min, keine Extrasystolen',
    },
    {
      id: 'B-05',
      name: 'Anna Bergmann',
      alter: 16,
      geschlecht: 'w',
      gewicht: 55,
      kurzbefund: 'Läuft umher, hält den linken Arm, ansprechbar und orientiert.',
      untersuchungsbefund: 'Geschlossene Unterarmfraktur links, Durchblutung intakt.',
      gehfaehig: true,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 18,
        herzfrequenz: 96,
        systolischerRR: 125,
        spo2: 98,
        gcs: 15,
        rekapzeit: 1.5,
        schmerz: 7,
      },
      probleme: [
        {
          id: 'schmerz-arm',
          offensichtlich: true,
          koerperregion: 'arm_links',
          label: 'Starke Schmerzen',
          beschreibung: 'Fehlstellung des linken Unterarms, hält ihn schonend, jede Bewegung sehr schmerzhaft.',
          behandeltDurch: ['paracetamol', 'immobilisation'],
          verlauf: { herzfrequenz: 1, atemfrequenz: 0.4, schmerz: 0.15 },
        },
      ],
      erwarteteSK: 'SK3',
    },
    {
      id: 'B-06',
      name: 'Tim Schuster',
      alter: 15,
      geschlecht: 'm',
      gewicht: 52,
      kurzbefund: 'Steht weinend am Fahrbahnrand, keine sichtbaren Verletzungen.',
      untersuchungsbefund: 'Körperlich unverletzt, ausgeprägte Hyperventilation, Angstreaktion.',
      gehfaehig: true,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 24,
        herzfrequenz: 110,
        systolischerRR: 130,
        spo2: 99,
        gcs: 15,
        rekapzeit: 1.5,
      },
      probleme: [
        {
          id: 'hyperventilation',
          offensichtlich: true,
          koerperregion: 'thorax',
          label: 'Hyperventilation / akute Belastungsreaktion',
          beschreibung: 'Weint, atmet sehr schnell und flach, Kribbeln in den Händen.',
          behandeltDurch: ['betreuung'],
          verlauf: { atemfrequenz: 0.8, herzfrequenz: 1 },
        },
      ],
      erwarteteSK: 'SK3',
    },
    {
      id: 'B-07',
      name: 'Klara Vogt',
      alter: 71,
      geschlecht: 'w',
      gewicht: 64,
      kurzbefund: 'Sitzt auf der Böschung, friert stark, kann nicht aufstehen.',
      untersuchungsbefund:
        'Rippenserienfraktur rechts, deutlich unterkühlt, Schmerzen bei Inspiration.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 22,
        herzfrequenz: 104,
        systolischerRR: 110,
        spo2: 94,
        gcs: 15,
        rekapzeit: 2,
        schmerz: 6,
      },
      probleme: [
        {
          id: 'hypothermie',
          offensichtlich: true,
          koerperregion: 'thorax',
          label: 'Auskühlung',
          beschreibung: 'Durchnässte Kleidung, liegt auf kaltem Asphalt, Haut kühl, beginnt zu zittern.',
          behandeltDurch: ['waermeerhalt'],
          verlauf: { rekapzeit: 0.06, systolischerRR: -1, herzfrequenz: 1 },
        },
      ],
      erwarteteSK: 'SK2',
    },
    {
      id: 'B-08',
      name: 'Nico Brandt',
      alter: 16,
      geschlecht: 'm',
      gewicht: 62,
      kurzbefund: 'Liegt neben dem Bus, benommen, öffnet die Augen auf Ansprache.',
      untersuchungsbefund: 'Schädelprellung, Amnesie für das Ereignis, keine Lateralisation.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 16,
        herzfrequenz: 88,
        systolischerRR: 120,
        spo2: 97,
        gcs: 12,
        rekapzeit: 1.5,
        schmerz: 3,
      },
      probleme: [
        {
          id: 'sht-leicht',
          offensichtlich: true,
          koerperregion: 'kopf',
          label: 'Leichtes Schädel-Hirn-Trauma',
          beschreibung: 'Erinnert sich nicht an den Unfall, fragt mehrfach dasselbe, Prellmarke am Hinterkopf.',
          behandeltDurch: ['immobilisation'],
          verlauf: { gcs: -0.12 },
        },
      ],
      erwarteteSK: 'SK2',
    },
    {
      id: 'B-09',
      name: 'Unbekannt (männlich)',
      alter: 60,
      geschlecht: 'm',
      gewicht: 82,
      kurzbefund: 'Liegt regungslos unter dem Bus, keine erkennbare Atmung.',
      untersuchungsbefund:
        'Nach Freimachen der Atemwege weiterhin keine Spontanatmung, schweres Thoraxtrauma.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: false,
      befolgtAufforderungen: false,
      startVitalwerte: {
        atemfrequenz: 0,
        herzfrequenz: 40,
        systolischerRR: 60,
        spo2: 70,
        gcs: 3,
        rekapzeit: 4,
      },
      probleme: [
        {
          id: 'atemstillstand',
          offensichtlich: true,
          koerperregion: 'thorax',
          label: 'Atemstillstand',
          beschreibung:
            'Keine Atembewegung, keine Reaktion auf Schmerzreiz, Haut fahl.',
          behandeltDurch: ['beatmung', 'intubation'],
          verlauf: { spo2: -8, herzfrequenz: -4, systolischerRR: -5 },
        },
      ],
      erwarteteSK: 'SK4',
      pupillen: 'weit',
      auskultation: 'kein Atemgeräusch beidseits',
      ekg: 'bradykarder Rhythmus ohne tastbaren Puls',
    },
    {
      id: 'B-10',
      name: 'Julia Petersen',
      alter: 38,
      geschlecht: 'w',
      gewicht: 66,
      kurzbefund: 'Begleitperson, geht umher, klagt über leichte Bauchschmerzen.',
      untersuchungsbefund:
        'Gurtmarke am Abdomen, zunehmender Druckschmerz - Verdacht auf innere Blutung.',
      gehfaehig: true,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 20,
        herzfrequenz: 100,
        systolischerRR: 118,
        spo2: 97,
        gcs: 15,
        rekapzeit: 1.8,
        schmerz: 3,
      },
      probleme: [
        {
          id: 'innere-blutung',
          koerperregion: 'abdomen',
          label: 'Intraabdominelle Blutung',
          beschreibung:
            'Bauchdecke zunehmend gespannt, Druckschmerz nimmt zu, Patientin wird stiller.',
          behandeltDurch: ['volumengabe'],
          startetNachMin: 2,
          verlauf: { systolischerRR: -5, herzfrequenz: 6, rekapzeit: 0.12, gcs: -0.15, schmerz: 0.2 },
        },
      ],
      erwarteteSK: 'SK3',
    },
  ],
  // Schematische, plausible Koordinaten (Raum Kreis Steinfurt, wie die
  // Fahrzeug-Bestückung) - keine echte Vermessung dieses Unfallorts, ein
  // "sinnvoller Standard" für Lagekarte und Verlegungsdauer
  // (→ `domain.geodaten`), wie schon die feste Rufgruppenliste.
  geodaten: {
    schluesselpunkte: {
      schadensstelle: { lat: 52.351, lon: 7.902 },
      ablage: { lat: 52.3505, lon: 7.901 },
      eingangssichtung: { lat: 52.3498, lon: 7.9 },
      zelt_rot: { lat: 52.3496, lon: 7.8998 },
      zelt_gelb: { lat: 52.3495, lon: 7.9 },
      zelt_gruen: { lat: 52.3494, lon: 7.9002 },
      ausgangssichtung: { lat: 52.3492, lon: 7.8999 },
      transport: { lat: 52.349, lon: 7.8995 },
      bereitstellungsraum: { lat: 52.3515, lon: 7.8985 },
    },
    routen: [
      { id: 'r-schadensstelle-eingangssichtung', von: 'schadensstelle', nach: 'eingangssichtung', distanzMeter: 150, sperraufschlagSek: 90 },
      { id: 'r-ablage-eingangssichtung', von: 'ablage', nach: 'eingangssichtung', distanzMeter: 100, sperraufschlagSek: 90 },
      // Zufahrt zur Schadensstelle beim Start gesperrt (Bus quer auf der
      // Fahrbahn) - Reserve-Fahrzeuge aus dem Bereitstellungsraum brauchen
      // dorthin einen festen Zeitaufschlag, keine Blockade.
      { id: 'r-bereitstellung-schadensstelle', von: 'bereitstellungsraum', nach: 'schadensstelle', distanzMeter: 350, sperraufschlagSek: 90, gesperrtBeimStart: true },
      { id: 'r-bereitstellung-ablage', von: 'bereitstellungsraum', nach: 'ablage', distanzMeter: 300, sperraufschlagSek: 90 },
      { id: 'r-bereitstellung-eingangssichtung', von: 'bereitstellungsraum', nach: 'eingangssichtung', distanzMeter: 280, sperraufschlagSek: 90 },
      { id: 'r-eingang-zeltrot', von: 'eingangssichtung', nach: 'zelt_rot', distanzMeter: 40, sperraufschlagSek: 60 },
      { id: 'r-eingang-zeltgelb', von: 'eingangssichtung', nach: 'zelt_gelb', distanzMeter: 45, sperraufschlagSek: 60 },
      { id: 'r-eingang-zeltgruen', von: 'eingangssichtung', nach: 'zelt_gruen', distanzMeter: 50, sperraufschlagSek: 60 },
      { id: 'r-zeltrot-zeltgelb', von: 'zelt_rot', nach: 'zelt_gelb', distanzMeter: 20, sperraufschlagSek: 30 },
      { id: 'r-zeltrot-zeltgruen', von: 'zelt_rot', nach: 'zelt_gruen', distanzMeter: 25, sperraufschlagSek: 30 },
      { id: 'r-zeltgelb-zeltgruen', von: 'zelt_gelb', nach: 'zelt_gruen', distanzMeter: 20, sperraufschlagSek: 30 },
      { id: 'r-zeltrot-ausgang', von: 'zelt_rot', nach: 'ausgangssichtung', distanzMeter: 35, sperraufschlagSek: 30 },
      { id: 'r-zeltgelb-ausgang', von: 'zelt_gelb', nach: 'ausgangssichtung', distanzMeter: 30, sperraufschlagSek: 30 },
      { id: 'r-zeltgruen-ausgang', von: 'zelt_gruen', nach: 'ausgangssichtung', distanzMeter: 35, sperraufschlagSek: 30 },
      { id: 'r-ausgang-transport', von: 'ausgangssichtung', nach: 'transport', distanzMeter: 60, sperraufschlagSek: 45 },
    ],
  },
  // Von der Übungsleitung live auslösbare Lageänderung (→ `modell.ereignis`,
  // `ui.ereignissepanel`) - existiert bis zum Auslösen nicht in der Übung,
  // taucht also nicht in `patienten` oben auf. Vitalwerte gegen tacSTART
  // geprüft wie die übrigen Patienten (→ `szenarien.liste`).
  ereignisse: [
    {
      id: 'zweiter-unfall',
      titel: 'Zweiter Unfall am Bus',
      beschreibung:
        'Ein PKW ist auf der Unfallstelle in den stehenden Bus gefahren - zwei weitere Verletzte gemeldet.',
      patienten: [
        {
          id: 'B-11',
          name: 'Tom Reinke',
          alter: 34,
          geschlecht: 'm',
          gewicht: 82,
          kurzbefund: 'PKW-Fahrer, steigt selbst aus, hält sich den Nacken.',
          untersuchungsbefund:
            'Schleudertrauma der Halswirbelsäule nach Auffahrunfall, Druckschmerz im Nacken, keine neurologischen Ausfälle.',
          gehfaehig: true,
          kritischeBlutung: false,
          spontanatmung: true,
          befolgtAufforderungen: true,
          startVitalwerte: {
            atemfrequenz: 18,
            herzfrequenz: 92,
            systolischerRR: 128,
            spo2: 98,
            gcs: 15,
            rekapzeit: 1.5,
            schmerz: 4,
          },
          probleme: [
            {
              id: 'hws-distorsion',
              offensichtlich: true,
              koerperregion: 'hals',
              label: 'HWS-Distorsion',
              beschreibung:
                'Nackenschmerzen und Bewegungseinschränkung nach Auffahrunfall, keine Kraft-/Gefühlsstörung.',
              behandeltDurch: ['immobilisation'],
              verlauf: { herzfrequenz: 1, schmerz: 0.05 },
            },
          ],
          erwarteteSK: 'SK3',
        },
        {
          id: 'B-12',
          name: 'Frauke Lindt',
          alter: 45,
          geschlecht: 'w',
          gewicht: 70,
          kurzbefund:
            'PKW-Beifahrerin, sitzt eingeklemmt im Fußraum, klagt über starke Schmerzen im Unterschenkel.',
          untersuchungsbefund:
            'Geschlossene Unterschenkelfraktur rechts durch Anprall am Armaturenbrett, Fehlstellung sichtbar, keine kritische Blutung.',
          gehfaehig: false,
          kritischeBlutung: false,
          spontanatmung: true,
          befolgtAufforderungen: true,
          startVitalwerte: {
            atemfrequenz: 22,
            herzfrequenz: 108,
            systolischerRR: 118,
            spo2: 96,
            gcs: 15,
            rekapzeit: 2,
            schmerz: 7,
          },
          probleme: [
            {
              id: 'fraktur-unterschenkel',
              offensichtlich: true,
              koerperregion: 'bein_rechts',
              label: 'Geschlossene Unterschenkelfraktur',
              beschreibung:
                'Sichtbare Fehlstellung des rechten Unterschenkels, zunehmende Schwellung, starke Schmerzen.',
              behandeltDurch: ['immobilisation'],
              verlauf: { herzfrequenz: 3, schmerz: 0.1, systolischerRR: -1 },
            },
          ],
          erwarteteSK: 'SK2',
        },
      ],
    },
  ],
};

const wohnungsbrand: Szenario = {
  id: 'wohnungsbrand',
  titel: 'Brand Mehrfamilienhaus',
  lagemeldung:
    'Kellerbrand mit starker Verrauchung im Treppenhaus. Sechs Bewohner über Drehleiter ' +
    'und Fluchthauben gerettet, Sammelstelle vor dem Gebäude.',
  einsatzhinweis:
    'Rauchgasintoxikationen können sich verzögert verschlechtern - konsequent Sauerstoff geben ' +
    'und Nachsichtung einplanen.',
  patienten: [
    {
      id: 'W-01',
      name: 'Petra Lange',
      alter: 58,
      geschlecht: 'w',
      gewicht: 72,
      kurzbefund: 'Rußspuren im Gesicht, verwirrt, kann nicht stehen.',
      untersuchungsbefund: 'Schwere Rauchgasintoxikation, Ruß in Mund und Nase, Heiserkeit.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 30,
        herzfrequenz: 122,
        systolischerRR: 105,
        spo2: 84,
        gcs: 13,
        rekapzeit: 2,
      },
      probleme: [
        {
          id: 'rauchgas-schwer',
          offensichtlich: true,
          koerperregion: 'hals',
          label: 'Schwere Rauchgasintoxikation',
          beschreibung: 'Ruß in Mund und Rachen, verbrannte Nasenhaare, heisere Stimme, hörbares Einatmen.',
          behandeltDurch: ['sauerstoffgabe', 'intubation'],
          verlauf: { spo2: -2, gcs: -0.25, atemfrequenz: 0.8, herzfrequenz: 3 },
        },
      ],
      erwarteteSK: 'SK1',
      auskultation: 'inspiratorischer Stridor, giemende Nebengeräusche beidseits',
    },
    {
      id: 'W-02',
      name: 'Aylin Demir',
      alter: 29,
      geschlecht: 'w',
      gewicht: 61,
      kurzbefund: 'Geht selbständig zur Sammelstelle, hustet.',
      untersuchungsbefund: 'Leichte Rauchgasexposition, keine Verbrennungen, vollständig orientiert.',
      gehfaehig: true,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 20,
        herzfrequenz: 92,
        systolischerRR: 128,
        spo2: 95,
        gcs: 15,
        rekapzeit: 1.5,
        schmerz: 4,
      },
      probleme: [
        {
          id: 'rauchgas-leicht',
          koerperregion: 'kopf',
          label: 'Leichte Rauchgasexposition',
          beschreibung: 'Klagt über Kopfschmerz und Übelkeit, wirkt benommen, Haut auffällig rosig.',
          behandeltDurch: ['sauerstoffgabe'],
          verlauf: { spo2: -0.4, herzfrequenz: 1 },
        },
      ],
      erwarteteSK: 'SK3',
    },
    {
      id: 'W-03',
      name: 'Bernd Schulte',
      alter: 47,
      geschlecht: 'm',
      gewicht: 84,
      kurzbefund: 'Sitzt am Boden, Verbrennungen an Armen und Brust.',
      untersuchungsbefund: 'Verbrennungen 2. Grades, ca. 25 Prozent KOF, starke Schmerzen.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 24,
        herzfrequenz: 116,
        systolischerRR: 100,
        spo2: 96,
        gcs: 15,
        rekapzeit: 2,
        schmerz: 9,
      },
      probleme: [
        {
          id: 'verbrennung',
          offensichtlich: true,
          koerperregion: 'thorax',
          label: 'Ausgedehnte Verbrennung',
          beschreibung: 'Blasenbildung an Armen und Rumpf, nässende Wundflächen, Patient friert.',
          behandeltDurch: ['volumengabe'],
          verlauf: { systolischerRR: -2.5, herzfrequenz: 1.5, rekapzeit: 0.08 },
        },
        {
          id: 'verbrennungsschmerz',
          offensichtlich: true,
          koerperregion: 'thorax',
          label: 'Stärkste Schmerzen',
          beschreibung: 'Stärkste Schmerzen, presst die Arme an den Körper, kaum zu beruhigen.',
          behandeltDurch: ['esketamin', 'morphin'],
          verlauf: { herzfrequenz: 1, atemfrequenz: 0.5, schmerz: 0.2 },
        },
      ],
      erwarteteSK: 'SK2',
    },
    {
      id: 'W-04',
      name: 'Marco Reiter',
      alter: 34,
      geschlecht: 'm',
      gewicht: 78,
      kurzbefund: 'Aus dem 2. OG gesprungen, liegt auf dem Rücken, klagt über Rückenschmerzen.',
      untersuchungsbefund: 'Druckschmerz LWS, Sensibilität der Beine erhalten, Sprunggelenk deformiert.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 20,
        herzfrequenz: 98,
        systolischerRR: 105,
        spo2: 97,
        gcs: 15,
        rekapzeit: 1.8,
        schmerz: 6,
      },
      probleme: [
        {
          id: 'wirbelsaeulentrauma',
          offensichtlich: true,
          koerperregion: 'ruecken',
          label: 'Verdacht auf Wirbelsäulenverletzung',
          beschreibung: 'Klagt über Kribbeln in beiden Beinen, Druckschmerz über der Brustwirbelsäule.',
          behandeltDurch: ['immobilisation'],
          verlauf: { herzfrequenz: 1.5, atemfrequenz: 0.3, schmerz: 0.1 },
        },
      ],
      erwarteteSK: 'SK2',
    },
    {
      id: 'W-05',
      name: 'Emilia Schulte',
      alter: 5,
      geschlecht: 'w',
      gewicht: 18,
      kurzbefund: 'Kleinkind, wird von Feuerwehr getragen, atmet sehr schnell, weint nicht.',
      untersuchungsbefund: 'Rauchgasintoxikation, Ruß im Rachen, zunehmend somnolent.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 34,
        herzfrequenz: 138,
        systolischerRR: 95,
        spo2: 88,
        gcs: 13,
        rekapzeit: 2,
      },
      probleme: [
        {
          id: 'rauchgas-kind',
          koerperregion: 'hals',
          label: 'Rauchgasintoxikation (Kind)',
          beschreibung: 'Auffällig ruhig, blasse Haut, Puls schnell und schwach zu tasten.',
          behandeltDurch: ['sauerstoffgabe', 'beatmung'],
          verlauf: { spo2: -2.5, gcs: -0.3, herzfrequenz: 2 },
        },
      ],
      erwarteteSK: 'SK1',
    },
    {
      id: 'W-06',
      name: 'Horst Kaminski',
      alter: 76,
      geschlecht: 'm',
      gewicht: 79,
      kurzbefund: 'Liegt auf einer Trage, blass, kaltschweißig, klagt über Brustenge.',
      untersuchungsbefund: 'Akutes Koronarsyndrom unter Stressbelastung, Kreislauf grenzwertig.',
      gehfaehig: false,
      kritischeBlutung: false,
      spontanatmung: true,
      befolgtAufforderungen: true,
      startVitalwerte: {
        atemfrequenz: 22,
        herzfrequenz: 108,
        systolischerRR: 85,
        spo2: 91,
        gcs: 15,
        rekapzeit: 2.5,
        schmerz: 6,
      },
      probleme: [
        {
          id: 'acs',
          offensichtlich: true,
          koerperregion: 'thorax',
          label: 'Akutes Koronarsyndrom',
          beschreibung: 'Klagt über Druck hinter dem Brustbein mit Ausstrahlung in den linken Arm, kaltschweißig.',
          behandeltDurch: ['sauerstoffgabe', 'morphin'],
          verlauf: { systolischerRR: -3, herzfrequenz: 2, spo2: -1, gcs: -0.1, schmerz: 0.15 },
        },
      ],
      erwarteteSK: 'SK1',
      ekg: 'ST-Hebungen in II, III und aVF',
    },
  ],
  geodaten: {
    ursprung: WOHNUNGSBRAND_URSPRUNG,
    schluesselpunkte: {
      schadensstelle: WOHNUNGSBRAND_URSPRUNG,
      ablage: lokalMZuGeo(WOHNUNGSBRAND_URSPRUNG, 10, -15),
      bereitstellungsraum: lokalMZuGeo(WOHNUNGSBRAND_URSPRUNG, -40, -30),
      eingangssichtung: lokalMZuGeo(WOHNUNGSBRAND_URSPRUNG, 5, 20),
      zelt_rot: lokalMZuGeo(WOHNUNGSBRAND_URSPRUNG, 0, 45),
      zelt_gelb: lokalMZuGeo(WOHNUNGSBRAND_URSPRUNG, 15, 45),
      zelt_gruen: lokalMZuGeo(WOHNUNGSBRAND_URSPRUNG, 30, 45),
      ausgangssichtung: lokalMZuGeo(WOHNUNGSBRAND_URSPRUNG, 15, 70),
      transport: lokalMZuGeo(WOHNUNGSBRAND_URSPRUNG, 15, 90),
    },
    // distanzMeter bewusst weggelassen - wird aus den obigen Koordinaten
    // berechnet (→ `domain.geodaten.haversine`).
    routen: [
      { id: 'wb-schadensstelle-eingangssichtung', von: 'schadensstelle', nach: 'eingangssichtung', sperraufschlagSek: 90 },
      { id: 'wb-ablage-eingangssichtung', von: 'ablage', nach: 'eingangssichtung', sperraufschlagSek: 90 },
      { id: 'wb-bereitstellung-schadensstelle', von: 'bereitstellungsraum', nach: 'schadensstelle', sperraufschlagSek: 90 },
      { id: 'wb-eingang-zeltrot', von: 'eingangssichtung', nach: 'zelt_rot', sperraufschlagSek: 60 },
      { id: 'wb-eingang-zeltgelb', von: 'eingangssichtung', nach: 'zelt_gelb', sperraufschlagSek: 60 },
      { id: 'wb-eingang-zeltgruen', von: 'eingangssichtung', nach: 'zelt_gruen', sperraufschlagSek: 60 },
      { id: 'wb-zeltrot-ausgang', von: 'zelt_rot', nach: 'ausgangssichtung', sperraufschlagSek: 30 },
      { id: 'wb-zeltgelb-ausgang', von: 'zelt_gelb', nach: 'ausgangssichtung', sperraufschlagSek: 30 },
      { id: 'wb-zeltgruen-ausgang', von: 'zelt_gruen', nach: 'ausgangssichtung', sperraufschlagSek: 30 },
      { id: 'wb-ausgang-transport', von: 'ausgangssichtung', nach: 'transport', sperraufschlagSek: 45 },
    ],
  },
};

export const SZENARIEN: Szenario[] = [busunfall, wohnungsbrand];

export function findeSzenario(id: string): Szenario | undefined {
  return SZENARIEN.find((szenario) => szenario.id === id);
}
